"""
Tests for GXA RDF output.

Loads a generated .ttl file and runs SPARQL queries to verify the graph
structure matches the expected unified Biolink pattern.

Requires: data/gxa_rdf/E-GEOD-5305.ttl (generated by `okn-wobd gxa convert`)
"""

import os
from pathlib import Path

import pytest
from rdflib import Graph, Namespace

# Namespaces used in queries
BIOLINK = Namespace("https://w3id.org/biolink/vocab/")
OKN = Namespace("http://purl.org/okn/wobd/")

TTL_PATH = Path(__file__).resolve().parent.parent / "data" / "gxa_rdf" / "E-GEOD-5305.ttl"

skip_if_no_ttl = pytest.mark.skipif(
    not TTL_PATH.exists(),
    reason=f"Test RDF file not found: {TTL_PATH}. Run: okn-wobd gxa convert --data-dir <gxa-dir> --output-dir data/gxa_rdf --experiment E-GEOD-5305",
)


@pytest.fixture(scope="module")
def graph():
    """Load the E-GEOD-5305 Turtle file into an rdflib Graph."""
    g = Graph()
    g.parse(str(TTL_PATH), format="turtle")
    return g


def _query(graph, sparql):
    """Run a SPARQL query and return results as a list of dicts."""
    results = graph.query(sparql)
    return [
        {str(var): row[i] for i, var in enumerate(results.vars)}
        for row in results
    ]


# ---------------------------------------------------------------------------
# Structure tests
# ---------------------------------------------------------------------------


@skip_if_no_ttl
def test_single_study_node(graph):
    """There should be exactly one Study node for this experiment."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        SELECT ?study WHERE { ?study a biolink:Study }
    """)
    assert len(rows) == 1
    assert "E-GEOD-5305" in str(rows[0]["study"])


@skip_if_no_ttl
def test_study_has_name_and_organism(graph):
    """Study should have a name and organism property."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        PREFIX okn: <http://purl.org/okn/wobd/>
        SELECT ?name ?organism WHERE {
            ?study a biolink:Study ;
                   biolink:name ?name ;
                   okn:organism ?organism .
        }
    """)
    assert len(rows) == 1
    assert str(rows[0]["name"]) == "E-GEOD-5305"
    assert "Mus musculus" in str(rows[0]["organism"])


@skip_if_no_ttl
def test_study_has_taxon(graph):
    """Study should link to an OrganismTaxon via in_taxon."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        SELECT ?taxon WHERE {
            ?study a biolink:Study ;
                   biolink:in_taxon ?taxon .
        }
    """)
    assert len(rows) == 1
    assert "10090" in str(rows[0]["taxon"])  # Mus musculus


@skip_if_no_ttl
def test_assay_nodes(graph):
    """There should be exactly 4 Assay nodes for E-GEOD-5305."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        SELECT ?assay WHERE { ?assay a biolink:Assay }
    """)
    assert len(rows) == 4


@skip_if_no_ttl
def test_study_has_output_to_assays(graph):
    """Study should connect to all assays via has_output."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        SELECT ?assay WHERE {
            ?study a biolink:Study ;
                   biolink:has_output ?assay .
            ?assay a biolink:Assay .
        }
    """)
    assert len(rows) == 4


@skip_if_no_ttl
def test_gene_nodes_exist(graph):
    """There should be many Gene nodes."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        SELECT (COUNT(?g) AS ?cnt) WHERE { ?g a biolink:Gene }
    """)
    count = int(rows[0]["cnt"])
    assert count > 1000, f"Expected >1000 genes, got {count}"


@skip_if_no_ttl
def test_genes_have_symbols(graph):
    """Gene nodes should have symbols."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        SELECT ?gene ?symbol WHERE {
            ?gene a biolink:Gene ;
                  biolink:symbol ?symbol .
        }
        LIMIT 5
    """)
    assert len(rows) == 5
    for row in rows:
        assert str(row["symbol"]).strip() != ""


# ---------------------------------------------------------------------------
# Differential expression tests
# ---------------------------------------------------------------------------


@skip_if_no_ttl
def test_de_associations_exist(graph):
    """There should be GeneExpressionMixin reified associations."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        SELECT (COUNT(?assoc) AS ?cnt) WHERE {
            ?assoc a biolink:GeneExpressionMixin .
        }
    """)
    count = int(rows[0]["cnt"])
    assert count > 100, f"Expected >100 DE associations, got {count}"


@skip_if_no_ttl
def test_de_associations_have_properties(graph):
    """DE associations should have log2fc, adj_p_value, and direction."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        PREFIX okn: <http://purl.org/okn/wobd/>
        SELECT ?assay ?gene ?fc ?pval ?dir WHERE {
            ?assoc a biolink:GeneExpressionMixin ;
                   biolink:subject ?assay ;
                   biolink:object ?gene ;
                   okn:log2fc ?fc ;
                   okn:adj_p_value ?pval ;
                   okn:direction ?dir .
        }
        LIMIT 10
    """)
    assert len(rows) == 10
    for row in rows:
        fc = float(str(row["fc"]))
        pval = float(str(row["pval"]))
        direction = str(row["dir"])
        assert -100 < fc < 100, f"Unreasonable log2fc: {fc}"
        assert 0 <= pval <= 1, f"p-value out of range: {pval}"
        assert direction in ("up", "down"), f"Bad direction: {direction}"


@skip_if_no_ttl
def test_de_assay_is_linked_to_study(graph):
    """DE assay subjects should be Assays that are outputs of the Study."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        SELECT DISTINCT ?assay WHERE {
            ?assoc a biolink:GeneExpressionMixin ;
                   biolink:subject ?assay .
            ?study a biolink:Study ;
                   biolink:has_output ?assay .
        }
    """)
    assert len(rows) > 0, "No DE assays linked back to study"


@skip_if_no_ttl
def test_de_object_is_gene(graph):
    """DE association objects should be Gene nodes."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        SELECT ?gene WHERE {
            ?assoc a biolink:GeneExpressionMixin ;
                   biolink:object ?gene .
            ?gene a biolink:Gene .
        }
        LIMIT 5
    """)
    assert len(rows) == 5


# ---------------------------------------------------------------------------
# Enrichment tests
# ---------------------------------------------------------------------------


@skip_if_no_ttl
def test_enrichment_associations_exist(graph):
    """There should be reified Association nodes for enrichment."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        PREFIX okn: <http://purl.org/okn/wobd/>
        SELECT (COUNT(?assoc) AS ?cnt) WHERE {
            ?assoc a biolink:Association ;
                   okn:enrichment_source ?source .
        }
    """)
    count = int(rows[0]["cnt"])
    assert count > 10, f"Expected >10 enrichment associations, got {count}"


@skip_if_no_ttl
def test_enrichment_has_properties(graph):
    """Enrichment associations should have adj_p_value and enrichment_source."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        PREFIX okn: <http://purl.org/okn/wobd/>
        SELECT ?assay ?term ?pval ?source WHERE {
            ?assoc a biolink:Association ;
                   biolink:subject ?assay ;
                   biolink:object ?term ;
                   okn:adj_p_value ?pval ;
                   okn:enrichment_source ?source .
        }
        LIMIT 10
    """)
    assert len(rows) == 10
    sources = {str(row["source"]) for row in rows}
    # Should see at least one of the enrichment sources
    valid_sources = {"GXA:GO", "GXA:Reactome", "GXA:InterPro"}
    assert sources & valid_sources, f"No valid enrichment sources found: {sources}"


@skip_if_no_ttl
def test_go_term_nodes_exist(graph):
    """There should be BiologicalProcess (GO) nodes."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        SELECT (COUNT(?t) AS ?cnt) WHERE { ?t a biolink:BiologicalProcess }
    """)
    count = int(rows[0]["cnt"])
    assert count > 0, "No GO term nodes found"


@skip_if_no_ttl
def test_pathway_nodes_exist(graph):
    """There should be Pathway (Reactome) nodes."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        SELECT (COUNT(?t) AS ?cnt) WHERE { ?t a biolink:Pathway }
    """)
    count = int(rows[0]["cnt"])
    assert count > 0, "No Reactome pathway nodes found"


@skip_if_no_ttl
def test_interpro_domain_nodes_exist(graph):
    """There should be ProteinDomain (InterPro) nodes."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        SELECT (COUNT(?t) AS ?cnt) WHERE { ?t a biolink:ProteinDomain }
    """)
    count = int(rows[0]["cnt"])
    assert count > 0, "No InterPro domain nodes found"


# ---------------------------------------------------------------------------
# Unified query test (same query works on ChatGEO and GXA data)
# ---------------------------------------------------------------------------


@skip_if_no_ttl
def test_unified_de_query(graph):
    """The unified DE query (shared with ChatGEO) should return results."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        PREFIX okn: <http://purl.org/okn/wobd/>

        SELECT ?study ?assay ?gene ?symbol ?fc ?pval WHERE {
            ?study a biolink:Study ;
                   biolink:has_output ?assay .
            ?assoc a biolink:GeneExpressionMixin ;
                   biolink:subject ?assay ;
                   biolink:object ?gene ;
                   okn:log2fc ?fc ;
                   okn:adj_p_value ?pval .
            ?gene biolink:symbol ?symbol .
        }
        ORDER BY ASC(?pval)
        LIMIT 20
    """)
    assert len(rows) == 20
    # Top results should have very low p-values
    top_pval = float(str(rows[0]["pval"]))
    assert top_pval < 0.01, f"Top DE gene p-value too high: {top_pval}"


@skip_if_no_ttl
def test_unified_enrichment_query(graph):
    """The unified enrichment query (shared with ChatGEO) should return results."""
    rows = _query(graph, """
        PREFIX biolink: <https://w3id.org/biolink/vocab/>
        PREFIX okn: <http://purl.org/okn/wobd/>

        SELECT ?assay ?term ?name ?pval ?source WHERE {
            ?assoc a biolink:Association ;
                   biolink:subject ?assay ;
                   biolink:object ?term ;
                   okn:adj_p_value ?pval ;
                   okn:enrichment_source ?source .
            ?term biolink:name ?name .
        }
        ORDER BY ASC(?pval)
        LIMIT 20
    """)
    assert len(rows) > 0, "Unified enrichment query returned no results"
